server:
  port: 8081
spring:
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    mode: html
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/2small?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: 6666
    password: 6666
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
mybatis:
  type-aliases-package: com.example.my2small.domain
  configuration:
    map-underscore-to-camel-case: true